### ISSUE TITLE
Insert File Issue

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#77] opened 2022-05-12 15:01 UTC
It works fine as long as you don't try to clear it and then download the **same** file.  Maybe this is how it is suppose to work but seemed strange.  If you try to download the same file after clearing, it won't download it.

Tom

**Comment by RandyLoeb** [comment] 2022-05-13 02:19
not sure what you mean. if you clear the text area, that means there's nothing to play, so if you try to download the audio there would be nothing. maybe i'm misunderstanding?

**Comment by grantbob** [comment] 2022-05-17 01:55
I think Tom means when you select "<-- Insert File" to import a file, then press the clear options, then "<-- Insert File" and choose the same file again it doesn't seem to import it this time.  Was able to reproduce on Chrome and Safari on a Mac.

**Comment by RandyLoeb** [comment] 2022-05-17 02:12
@grantbob @nolleto1 @LongIslandCW thanks for clarifying, I was able to reproduce. It should be fixed now on beta site https://longislandcw.github.io/morsebrowser/dev/  please review and close issue if all good.

**Comment by nolleto1** [comment] 2022-05-17 02:47
Guess I need to work on stating thing more clearly.  😄  Sorry for the
confusion Randy.
Tom AB5TN

**Comment by grantbob** [comment] 2022-05-17 02:52
> @grantbob @nolleto1 @LongIslandCW thanks for clarifying, I was able to reproduce. It should be fixed now on beta site https://longislandcw.github.io/morsebrowser/dev/ please review and close issue if all good.

Seems to be fixed in the dev environment to me in Chrome and Safari on the Mac.

**Comment by RandyLoeb** [comment] 2022-05-17 03:06
Great thanks, closing it out.

**Closed by RandyLoeb** 2022-05-17 03:06 UTC
